on-quest-start-commands:
  - '{0} [consolecmd] bc %player% started quest %quest_name%'
on-quest-finish-commands: []
on-quest-cancel-commands: []
on-stage-change-commands:
  - '[message] &a[Nhiệm vụ] Hoàn thành giai đoạn &2%old_stage%/%max_stage% !'
  - '{10} [title] &f;&a&l&oHoàn thành giai đoạn &2%old_stage%/%max_stage%'
  - '{30} [title] &f;&a&l&oGiai đoạn hiện tại: &2%new_stage%/%max_stage%'
no-quit-quests:
  - main_1
  - main_2
  - main_3
  - main_4
  - main_5
  - main_6
  - main_7
  - main_8
  - main_9
  - main_10
category:
  main:
    name: Nhiệm vụ chính quyến
    cooldown:
      enable: false
    random:
      enable: false
    list:
      - main1
      - main2
      - main3
      - main4
  daily:
    name: Nhiệm vụ hằng ngày
    cooldown:
      enable: true
      type: DAILY
    random:
      enable: true
      amount: 2
    list:
      - daily1
      - daily2
      - daily3
      - daily4

featherboard:
  enable: true
  board: quest
  quests:
    - q1
    - q2
    - q3