name: Simple example quest
desc: Duong ve nha la vao tim ta
reward-desc:
  - '+ 100 Tokens'
  - '+ 200,000 Exp'
# Can remove if you did't want to set
requirement-desc: Can hoan thanh q1 hoac q2 va lam sau ngay 10/10/2020
requirements:
  0:
    type: QUEST_DONE
    value: 'or;q1;q2'
  1:
    type: DATE
    value: '> 10/10/2020'
reward-commands:
  - '{5} [consolecmd] bc %player% got the rewards of %quest_name%'
stages:
  0:
    type: CONVERSATION
    objective: Nói chuyện với Soragari
    count: 5
    data:
      npc-id: 3
      c-0: '&fChào mừng &a%player% &fđến với Sora World'
      c-1: '&fChào mừng &a%player% &fđến với Sora World 2'
      c-2: '&fChào mừng &a%player% &fđến với Sora World 3'
      c-3: '&fChào mừng &a%player% &fđến với Sora World 4'
      c-4: '&fChào mừng &a%player% &fđến với Sora World 5'